# Generated by Django 5.0 on 2025-12-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_path', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ANALYSIS', 'Analysis'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ERROR_LLM', 'Error_LLM'), ('ERROR_DOWNLOAD', 'Error_download')], default='RECEIVED', max_length=20)),
                ('transcription', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('hook', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
