# Generated by Django 5.0 on 2025-12-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorecord',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('ANALYSIS', 'Analysis'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REGENERATE', 'Regenerate'), ('ERROR_LLM', 'Error_LLM'), ('ERROR_DOWNLOAD', 'Error_download')], default='RECEIVED', max_length=20),
        ),
    ]
